version: "3"
services:
  zmq:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - $HOME/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      # TUNNEL_HOST: bchn-mainnet
      # REMOTE_HOST: ec2-13-251-63-215.ap-southeast-1.compute.amazonaws.com
      TUNNEL_HOST: bchn-chipnet
      REMOTE_HOST: ec2-18-138-226-25.ap-southeast-1.compute.amazonaws.com
      LOCAL_PORT: 28332
      REMOTE_PORT: 28332
  postgres:
    image: "postgres:11.1-alpine"
    expose:
      - "5432"
    env_file:
      - .env_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    build: .
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    ports:
      - "8000:8000"
    env_file:
      - .env_dev
    depends_on:
      - postgres
    volumes:
      - ./:/code
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis-data:/data
