version: "3"
services:
  postgres:
    image: "postgres:15"
    ports:
      - 5432:5432
    env_file:
      - .env_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bcmr-network
  backend:
    build: .
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    ports:
      - 8000:8000
    env_file:
      - .env_dev
    depends_on:
      - postgres
    volumes:
      - ./:/code
    networks:
      - bcmr-network
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis-data:/data
    networks:
      - bcmr-network
    
volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/bcmr-pgdata
      o: bind

networks:
  bcmr-network: {}


